### ISSUE TITLE
ce_projectileoutlines_color_xxx needs clientscheme.res color support

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/CastingEssentials#1]

**Comment by dalegaard** [comment]
What should the names of the colors be?

**Comment by Wiethoofd** [comment]
Any color defined in the clientscheme in the `Colors { }` section.

To check which color names are available open `showschemevisualizer clientscheme` in console.

**Comment by PazerOP** [comment]
There is now support for named colors on all convars.
