### ISSUE TITLE
No valid signature for plugin.

### ISSUE THREAD

**Issue by aaalek** [PazerOP/CastingEssentials#110]
Plugin doesn't load on boot, using plugin_load to manually load the plugin, it says the file has no valid signature and cannot load.

] plugin_load addons/castingessentials
No valid signature found for f:\program files (x86)\steam\steamapps\common\team fortress 2\tf\custom\castingessentials\addons\castingessentials.dll
Unable to load plugin "addons/castingessentials"

**Comment by dalegaard** [comment]
This happens because you are not starting the game on insecure mode. Add `-insecure` to your game launch options.
