### ISSUE TITLE
Add support for damage numbers/hitsounds in STV.

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/CastingEssentials#29]

**Comment by PazerOP** [comment]
It appears this is not possible without additional server support.

**Comment by dalegaard** [comment]
srctv+ provides the server side support for this. I'll be releasing it in the coming days.

**Comment by PazerOP** [comment]
@dalegaard Are you planning on compiling a version suitable for Windows servers? According to Arie, the na.serveme.tf servers run on windows (???), which is why they're not currently running your plugin.

**Comment by dalegaard** [comment]
I am, yes.

**Comment by PazerOP** [comment]
Added in https://github.com/PazerOP/CastingEssentials/commit/9607814d875a90ea29b398296675f4afc0e73ac8
