### ISSUE TITLE
Autocamera cycle prev inconsistent behaviour from next

### ISSUE THREAD

**Issue by Wiethoofd** [PazerOP/CastingEssentials#49]
next 'snaps' to the nearest defined static autocamera
prev will go to the last defined autocamera in the vdf

**Comment by PazerOP** [comment]
"Fixed" in https://github.com/PazerOP/CastingEssentials/commit/f214c2d68b7cf6dfffe0f3135c8e6ffb2732b9d9. The two now have identical behavior when not on an autocamera.

**Comment by Wiethoofd** [comment]
This fix undid the behaviour I keep expecting when using 'next' to *snap* to the nearest autocamera, it doesn't happen anymore like it did in the version before this release and now (I assume) prioritizes file order/LoS over actual proximity (which I preferred for consistency of getting an angle which shows players)
