### ISSUE TITLE
Disable professional killstreak eye effects when spectating firstperson

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/CastingEssentials#52]

**Comment by Wiethoofd** [comment]
This can be (partially) achieved by modifying the vmt files loading the particle.

e.g. Extract `materials\effects\smoke\smokelit.vmt` and add the following will delay the disguise smoke to be less obnoxious when spectating a spy.
```
$startfadesize .05
$endfadesize .25
```

Alternatively there are some hidden 'client, launcher' convars that control when the killstreak eye effects will appear:
```
tf_killstreakeyes_maxkills : 10 : "cl", "launcher" : kills to get the max eye glow effect
tf_killstreakeyes_minkills : 5  : "cl", "launcher" : min kills to get base eyeglow
```
Unlocking and/or overriding those might be an easier solution.

**Comment by PazerOP** [comment]
These cvars are currently inaccessible because they have the `FCVAR_DEVELOPMENTONLY` flag. In r20, you will be able to add/remove that flag using `ce_consoletools_flags_remove tf_killstreakeyes_min/maxkills devonly`. Once that flag is removed, you could "disable" killstreak eye effects altogether by setting the min and max to some really high number that players will never get to.

I'm still investigating being able to hide the particle effect when you're in firstperson.

**Comment by PazerOP** [comment]
Fixed in https://github.com/PazerOP/CastingEssentials/commit/7261697f8e718a7789de63a0aa53de4275bb1406.
