### ISSUE TITLE
Block player weapon inspecting animations

### ISSUE THREAD

**Issue by Wiethoofd** [PazerOP/CastingEssentials#53]
SourceTV replicates when the player is inspecting his/her weapon, which might happen mid fight (and unbeknownst to the player who has their viewmodels disabled).

Completely disabling weapon inspection animations and making them observer controllable might be a nice option for consistent and 'not moving' weapon models when spectating.

**Comment by PazerOP** [comment]
Got a preliminary version of "block inspect animations" working. It's quite a bit of a hack though, so it may not work perfectly in all scenarios. All it does is just replace incoming inspect animations from the server with the idle animation. There's no way to know what would "normally" be playing at that time, but as far as I know you can't do anything else while inspecting your weapon (not even reloading) so it should be fine.

**Comment by PazerOP** [comment]
Committed in https://github.com/PazerOP/CastingEssentials/commit/8524dee376c077bf238e6b4895eeb28d475188df.
