### ISSUE TITLE
Steam Rich Presence broke after Valve's recent changes

### ISSUE THREAD

**Issue by Wiethoofd** [PazerOP/CastingEssentials#54]
Valve [updated](http://www.teamfortress.com/post.php?id=38643) the Steam Rich Presence, the module still loads, but does not display the value set for `ce_steamtools_rich_presence` on the 'Server' line anymore when viewing 'Game Info' for the user.

Additionally being able to control what is being displayed in the main menu friendslist when spectating in an STV might be useful.

**Comment by PazerOP** [comment]
Fixed in 757b939f15fd3d1eb3ca32e52bd39eb45a7410e1. Wasn't technically broken either, just required that you change `ce_steamtools_rich_presence` after you had already joined a game so it would override the game's rich presence string. Now, CE applies the rich presence settings every 10 seconds.
