### ISSUE TITLE
Status Effect Indicators

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/CastingEssentials#59]

**Comment by Wiethoofd** [comment]
There are already player status icon indicators available in SpectatorTournamentGUIHealth, similar to HudPlayerHealth, but inactive and have limited control over positioning in both files.

**Comment by PazerOP** [comment]
Added in https://github.com/PazerOP/CastingEssentials/commit/787ba9ec791d40e52605953b4d7a0d3e1674a51f.
