### ISSUE TITLE
Additional weapon charge bars

### ISSUE THREAD

**Issue by Wiethoofd** [PazerOP/CastingEssentials#77]
Currently only the 3 soldier banners are supported, but with a lot of weapons also having charge bars in the regular hud some wouldn't hurt to also be in the playerpanels in the spectator hud.

In no particular order:
* Scout primaries/throwables
* Sniper weapon charge/throwables
* Heavy edibles
* Phlogistinator
* Demo shield charge
* Cleaner's Carbine
* Engineer Ammo (without the % in labeltext ofc)
* Spy Cloak/Feign

No clue what should happen if a scout for instance has a Baby Face's Blaster + Mad Milk + Sandman equipped which chargebar to prioritize or have them swap based on active weapon.

**Comment by PazerOP** [comment]
Added in https://github.com/PazerOP/CastingEssentials/commit/f16752e0d5cf748edb6711644c780c8ded4a4cd1 and https://github.com/PazerOP/CastingEssentials/commit/6c1aed0494cfa02ee05efb9c47c71522facac7aa.
